apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-frontend-feilmeldinger
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  ingresses:
    - {{ingress}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        diskSize: 10
        pointInTimeRecovery: false
        diskAutoresize: true
        databases:
          - name: flex-frontend-feilmeldinger-db
            envVarPrefix: DATABASE
        maintenance:
          day: 2
          hour: 2
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
https://nav-it:
  slack:
    com/archives/C04HE1B49JP/p1678187710648639?thread_ts=1677848190:
      909109&cid=C04HE1B49JP:
